openapi: 3.0.0
info:
  title: "Hot bot API"
  version: "0.0.1"
  contact:
    name: HotCodeGroup
    url: https://github.com/HotCodeGroup
paths:
  /users/{userID}:
    get:
      tags:
        - users
      summary: Get user info by ID
      operationId: getUser
      parameters:
        - name: userID
          in: path
          description: ID of user that needs to be get
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
        - active
      properties:
        id:
          type: integer
          format: int64
          description: 'user ID'
          example: 1
        username:
          type: string
          description: 'name for login'
          example: 'xXxNaGiBaToRxXx'
        email:
          type: string
          description: 'User email'
          example: 'vitalik2007@gmail.com'
        firstName:
          type: string
          description: "User first name"
          example: 'Vitaly'
        lastName:
          type: string
          description: "User last name"
          example: 'Pryahov'
        active:
          type: boolean
          description: "Returns if a profile is blocked"
          example: true
        

